postgres:
  image: postgres:9.6.3
  environment:
    POSTGRES_USER: budgiex
    POSTGRES_PASSWORD: "123456"
    POSTGRES_DB: budgiex
  ports:
    - 5432:5432
  volumes:
    - ./sql/:/docker-entrypoint-initdb.d/
